site_name: pypedream
repo_url: https://bitbucket.org/mintel/pypedream
repo_name: pypedream
site_description: "Data processing via distributed directed graph."
theme: simplex
pages:
  - 'Home': 'index.md'
